'use server'

export async function GET() {


const regions = [
    {  regionCode: "USARL", regionName: "Adventist Robotics League" },
    {  regionCode: "USAL", regionName: "Alabama" },
    {  regionCode: "USAK", regionName: "Alaska" },
    {  regionCode: "CAAB", regionName: "Alberta" },
    {  regionCode: "USAZ", regionName: "Arizona" },
    {  regionCode: "USAR", regionName: "Arkansas" },
    {  regionCode: "AU", regionName: "Australia" },
    {  regionCode: "BR", regionName: "Brazil" },
    {  regionCode: "CABC", regionName: "British Columbia" },
    {  regionCode: "USCALA", regionName: "California - Los Angeles" },
    {  regionCode: "USCANO", regionName: "California - Northern" },
    {  regionCode: "USCASD", regionName: "California - San Diego" },
    {  regionCode: "USCHS", regionName: "Chesapeake" },
    {  regionCode: "CN", regionName: "China" },
    {  regionCode: "TW", regionName: "Chinese Taipei" },
    {  regionCode: "USCO", regionName: "Colorado" },
    {  regionCode: "USCT", regionName: "Connecticut" },
    {  regionCode: "USDE", regionName: "Delaware" },
    {  regionCode: "USFL", regionName: "Florida" },
    {  regionCode: "USFCT", regionName: "Four Corners Tribal Teams" },
    {  regionCode: "FR", regionName: "France" },
    {  regionCode: "USGA", regionName: "Georgia" },
    {  regionCode: "DE", regionName: "Germany" },
    {  regionCode: "GR", regionName: "Greece" },
    {  regionCode: "USHI", regionName: "Hawaii" },
    {  regionCode: "HU", regionName: "Hungary" },
    {  regionCode: "USID", regionName: "Idaho" },
    {  regionCode: "USIL", regionName: "Illinois" },
    {  regionCode: "ID", regionName: "India" },
    {  regionCode: "USIN", regionName: "Indiana" },
    {  regionCode: "IN", regionName: "Indonesia" },
    {  regionCode: "USIA", regionName: "Iowa" },
    {  regionCode: "IL", regionName: "Israel" },
    {  regionCode: "IT", regionName: "Italy" },
    {  regionCode: "JM", regionName: "Jamaica" },
    {  regionCode: "KZ", regionName: "Kazakhstan" },
    {  regionCode: "USKY", regionName: "Kentucky" },
    {  regionCode: "LY", regionName: "Libya" },
    {  regionCode: "LT", regionName: "Lithuania" },
    {  regionCode: "USLAU", regionName: "Los Angeles Unified School District" },
    {  regionCode: "USLA", regionName: "Louisiana" },
    {  regionCode: "MY", regionName: "Malaysia" },
    {  regionCode: "USMA", regionName: "Massachusetts" },
    {  regionCode: "MX", regionName: "Mexico" },
    {  regionCode: "USMI", regionName: "Michigan - FiM" },
    {  regionCode: "ONODOD", regionName: "Military and Diplomatic" },
    {  regionCode: "USMN", regionName: "Minnesota" },
    {  regionCode: "USMS", regionName: "Mississippi" },
    {  regionCode: "USMOKS", regionName: "Missouri/Kansas" },
    {  regionCode: "MD", regionName: "Moldova" },
    {  regionCode: "USMT", regionName: "Montana" },
    {  regionCode: "MA", regionName: "Morocco" },
    {  regionCode: "USNE", regionName: "Nebraska" },
    {  regionCode: "NL", regionName: "Netherlands" },
    {  regionCode: "USNV", regionName: "Nevada" },
    {  regionCode: "USNH", regionName: "New Hampshire" },
    {  regionCode: "USNJ", regionName: "New Jersey" },
    {  regionCode: "USNM", regionName: "New Mexico" },
    {  regionCode: "USNYEX", regionName: "New York - Excelsior" },
    {  regionCode: "USNYLI", regionName: "New York - Long Island" },
    {  regionCode: "USNYNY", regionName: "New York - NYC" },
    {  regionCode: "NZ", regionName: "New Zealand" },
    {  regionCode: "NF", regionName: "Newfoundland and Labrador" },
    {  regionCode: "NG", regionName: "Nigeria" },
    {  regionCode: "USNC", regionName: "North Carolina" },
    {  regionCode: "USND", regionName: "North Dakota" },
    {  regionCode: "USOH", regionName: "Ohio" },
    {  regionCode: "USOK", regionName: "Oklahoma" },
    {  regionCode: "CAON", regionName: "Ontario" },
    {  regionCode: "USOR", regionName: "Oregon" },
    {  regionCode: "USPA", regionName: "Pennsylvania" },
    {  regionCode: "PL", regionName: "Poland" },
    {  regionCode: "USPR", regionName: "Puerto Rico" },
    {  regionCode: "QA", regionName: "Qatar" },
    {  regionCode: "CAQC", regionName: "Québec" },
    {  regionCode: "USRI", regionName: "Rhode Island" },
    {  regionCode: "RO", regionName: "Romania" },
    {  regionCode: "SA", regionName: "Saudi Arabia" },
    {  regionCode: "ZA", regionName: "South Africa" },
    {  regionCode: "USSC", regionName: "South Carolina" },
    {  regionCode: "KR", regionName: "South Korea" },
    {  regionCode: "ES", regionName: "Spain" },
    {  regionCode: "USTN", regionName: "Tennessee" },
    {  regionCode: "USTX", regionName: "Texas - FIT" },
    {  regionCode: "USTXHO", regionName: "Texas - Houston" },
    {  regionCode: "TH", regionName: "Thailand" },
    {  regionCode: "TR", regionName: "Türkiye" },
    {  regionCode: "UA", regionName: "Ukraine" },
    {  regionCode: "GB", regionName: "United Kingdom" },
    {  regionCode: "USUT", regionName: "Utah" },
    {  regionCode: "USVT", regionName: "Vermont" },
    {  regionCode: "VN", regionName: "Vietnam" },
    {  regionCode: "USWA", regionName: "Washington" },
    {  regionCode: "USWI", regionName: "Wisconsin" },
    {  regionCode: "USWY", regionName: "Wyoming" },


]





    return new Response(JSON.stringify(regions), {
        status: 200,
        headers: {
            'Content-Type': 'application/json'
        }
  })
}